boot_multicons=YES
boot_serial=YES
comconsole_speed=115200
comconsole_port="0x2f8
console=comconsole,efi
cryptodev_load=YES
zfs_load=YES
net.fibs=256
kern.racct.enable=1
fusefs_load=YES

# boot_verbose="YES"
