loader="uefi"
cpu="4"
cpu_sockets="1"
cpu_cores="2"
cpu_threads="2"
memory=2048M
disk0_type="virtio-blk"
disk0_dev="zvol"
disk0_name="disk0"
disk0_size="4G"
loader="bhyveload"
comports="com1"
graphics="no"
xhci_mouse="no"
wired_memory="yes"
network0_type="virtio-net"
network0_switch="bridge1"
uefi_vars="yes"
